### ISSUE TITLE
Options starting with `--no` are not passed to anvil

### ISSUE THREAD

**Issue by bernard-wagner** [usecannon/cannon#1321]
Commander.js treats options starting with `--no` as negating options and consequently options such as `--no-cors` and `--no-storage-caching` are not passed to `anvil`. Instead, the options are registered as `{ "cors": false }` and are then skipped by `pickAnvilOptions()`.

Easy to test is with `cannon clean --no-confirm`.

**Comment by bernard-wagner** [comment]
Got a potential fix, but maybe someone else has a better approach:

Changes to commander.js:
https://github.com/bernard-wagner/commander.js/commit/f037c1b06b5e0e0d40cde45defc31b3f32ce14f7

Cannon changes:
https://github.com/bernard-wagner/cannon/commit/467a1121715b7ca0ad958b56d002da841dbfc7d7

**Comment by bernard-wagner** [comment]
PR for Commander.js changes.

https://github.com/tj/commander.js/pull/2238

**Comment by noahlitvin** [comment]
Closing, this is resolved in the latest release. Ty!
