### ISSUE TITLE
Improve plug-in detection consistency

### ISSUE THREAD

**Issue by noahlitvin** [usecannon/cannon#141]
There's some inconsistency when installing/detecting the `@synthetixio/router` plug-in from inside/outside npm projects. I've noted this a few times, but haven't figured out the underlying cause. (I think sometimes there's a need to delete the plugins folder in the shared directory and reinstall?)

**Comment by dbeal-eth** [comment]
@mjlescano do you want to update this issue? seems like its done but I a m not sure

**Comment by dbeal-eth** [comment]
fixed by @mjlescano
