### ISSUE TITLE
`cannon build` should infer `chainId` when `--provider-url` is specified

### ISSUE THREAD

**Issue by dbeal-eth** [usecannon/cannon#184]
When running cannon build on a non cannon network, and `--provider-url` is specified without specifying `--chain-id`, `chainId` should be set to the resolved chainId from `getNetwork` call on provider.

**Comment by aminlatifi** [comment]
<img width="551" alt="image" src="https://github.com/usecannon/cannon/assets/5684607/a346c250-8b3d-40d3-bb1e-18f6369ba877">

If the above scenario is the expectation, the logic has already been implemented and there is no need for any change.
@dbeal-eth  It seems `--provider-url` isn't used without `--chain-id`. If it's right, I think we can close this issue.

**Comment by dbeal-eth** [comment]
the idea of this issue is that it is possible to *derive* `--chain-id` from `--provider-url`, if it is supplied.

for example, right now if a user who is not using Frame wants to deploy to goerli, they have to type (for example):

```
cannon build cannonfile.toml --chain-id 5 --provider-url https://goerli.infura.io/arstarstarsta
```

in this case, it is annoying to have to type `--chain-id`, because technically cannon could figure out that you want to deploy to `--chain-id 5` just from the specification of the `--provider-url` argument, since the chain id can be queried from the provider with `provider.getNetwork()` call. so with this change, we would expect to be able to run a command like:

```
cannon build cannonfile.toml --provider-url https://goerli.infura.io/arstarstarsta
```

**Comment by dbeal-eth** [comment]
`--chain-id` is still useful if buildign with frame, or if you are on CI and want to add a sanity check to make sure you are on the correct network
