### ISSUE TITLE
CLI build command output should reflect the loader scheme

### ISSUE THREAD

**Issue by noahlitvin** [usecannon/cannon#191]
In the [CLI for build command](https://github.com/usecannon/cannon/blob/main/packages/cli/src/commands/build.ts#L139), the output says the package is being fetched from IPFS. This should be updated based on whether the runtime is using ["file" instead of "ipfs"](https://github.com/usecannon/cannon/blob/main/packages/cli/src/commands/build.ts#L125).

**Comment by aminlatifi** [comment]
https://github.com/usecannon/cannon/blob/main/packages/cli/src/commands/build.ts#L110
