### ISSUE TITLE
Package spec

### ISSUE THREAD

**Issue by tuler** [usecannon/cannon#196]
Really interesting project! Solves a real issue of packaging and composing deployments.

It would be interesting to first define a spec for the deployment package format.
And then build on top of that, the CLI, storage options (onchain, offchain), and web clients.
It would also enable import strategies from deployments that already exist, i.e. as hardhat-deploy deployments.

**Comment by noahlitvin** [comment]
Hey! Sorry for the slow response.

I think it'd be great for our documentation to more clearly explain the package format. I'll make a note to revisit this on the next pass on the docs. Thanks for raising this, will close the issue for now.
