### ISSUE TITLE
Check that the current version of anvil supports PUSH0 opcode

### ISSUE THREAD

**Issue by noahlitvin** [usecannon/cannon#201]

**Comment by dbeal-eth** [comment]
a better way to handle this would be to record the current network version of the compiled contracts in the artiefacts, adn then verify support for that version on startup

**Comment by noahlitvin** [comment]
Also check if the anvil version is too old because dump format changed.

**Comment by FuzzB0t** [comment]
In case this wasnt clarified yet, I just checked the foundry v0.8.20 [release] (https://github.com/ethereum/solidity/releases/tag/v0.8.20) and the assembler now uses PUSH0.
