### ISSUE TITLE
Partial Deployments CLI output should be the last thing printed to console

### ISSUE THREAD

**Issue by noahlitvin** [usecannon/cannon#207]
The yellow text should be the last thing output by the CLI (after TRANSACTIONS: and EXTRA DATA:)

It should also suggest publishing the ipfs package with https://github.com/usecannon/cannon/issues/206

**Comment by mohammadranjbarz** [comment]
Are you talking about this part?
<img width="1204" alt="Screen Shot 1402-03-10 at 15 34 28" src="https://github.com/usecannon/cannon/assets/9850545/abd9fc90-f7e7-4133-8af2-e03ae3244462">

Can you provide more information to change where, and with which command I can see that to change it?

**Comment by dbeal-eth** [comment]
> Are you talking about this part? <img alt="Screen Shot 1402-03-10 at 15 34 28" width="1204" src="https://user-images.githubusercontent.com/9850545/242268861-abd9fc90-f7e7-4133-8af2-e03ae3244462.png">
> 
> Can you provide more information to change where, and with which command I can see that to change it?

do you see where it prints `Successfully built package greeter-foundry:2.4.14`?

it should print that message after the `CONTRACTS:` output and table, basically
