### ISSUE TITLE
Add decoding of Error(string) and Panic(uint)

### ISSUE THREAD

**Issue by mjlescano** [usecannon/cannon#208]
It should be possilble to decode Error(string) and Panic(uint) opcodes always, just in case the user inputs them without realizing what they are. you can see a sample of this in the builder/src/error/index.ts file, its pretty slick.

**Comment by aminlatifi** [comment]
@noahlitvin I tried running `ts-node packages/cli/bin/cannon.ts decode greeter-foundry:2.4.15 0x4e487b710000000000000000000000000000000000000000000000000000000000000001`
But it's the output
Error: Could not decode transaction data

Nevertheless, I could reproduce error decoding by creating test methods throwing errors (by assert, require or custom error).

**Comment by aminlatifi** [comment]
It took longer than expected because I face an issue with decoding errors in the interact mode! I tried to find a solution to not clutter the code a lot.
