### ISSUE TITLE
The decode command is not working for `setMaxMarketValue(bytes32 _marketKey,uint256 _maxMarketValue)`

### ISSUE THREAD

**Issue by mjlescano** [usecannon/cannon#209]
For nested function decode, when I run a command like `node packages/cli/dist/bin/cannon.js decode synthetix-omnibus:latest --chain-id 5 0x633026dd73444f474550455250000000000000000000000000000000000000000000000000000000000000000000000000000000000000000039e7139a8c08fa06000000` (which should decode to `setMaxMarketValue(bytes32 _marketKey,uint256 _maxMarketValue)` on SpotMarketProxy), it says that its not found.

**Comment by aminlatifi** [comment]
In loaded ABIs there isn't any method with name `setMaxMarketValue`
