### ISSUE TITLE
prevent `control-C` in the middle of a live network build

### ISSUE THREAD

**Issue by dbeal-eth** [usecannon/cannon#224]
if a user cancels a build on a live network, any state from the build will be lost since cannon did not have a chance to save it.

instead, if the user presses control-C, cannon should be allowed to finish the current step. once the step completes, it should exit after it has saved the latest state data.

**Comment by aminlatifi** [comment]
@dbeal-eth It's pretty ambiguous for me how to do it. Honestly, I don't have a deep knowledge of the build process steps like state, actions, layer, etc... 
I assume something must be done one the `buildLayer` function, but not sure what must me save and what must be skipped 
https://github.com/usecannon/cannon/blob/cb5a4d1cc32c322aaa7db5a54727bc225a922c38/packages/builder/src/builder.ts#LL182C23-L182C33
