### ISSUE TITLE
Ignore node_modules in parent folders

### ISSUE THREAD

**Issue by noahlitvin** [usecannon/cannon#266]
It looks like npm scans parent directories to find node_modules when running commands like `npm i` (within `cannon plugin add`). We should avoid this.

This should be tested, but we believe the solution should consist of adding a `package.json` in the plugins directory when intialized. (Add a package.json in a parent directory to test.)

**Comment by aminlatifi** [comment]
@noahlitvin I tested on my machine, removed the plugin directory, and installed one plugin by:
`cannon plugin add cannon-plugin-router`
I ran the above command in the cannon source code directory!
The plugin is only installed in the plugin directory and an appropriate `package.json` file is created in that directory
```json
{
  "dependencies": {
    "cannon-plugin-router": "^1.0.15"
  }
}
```
Is there any sign that the parent node_modules are scanned?

**Comment by noahlitvin** [comment]
@dbeal-eth @mjlescano do we remember where this one came from?

**Comment by dbeal-eth** [comment]
It came from talking with voltz I believe, they had that plugin issue and we found out their dev had a package Json in their home dir

**Comment by aminlatifi** [comment]
Thanks @dbeal-eth for the context
https://github.com/usecannon/cannon/pull/303 ready for review
