### ISSUE TITLE
Throw error on factory or extra where event is not found

### ISSUE THREAD

**Issue by dbeal-eth** [usecannon/cannon#268]
Currently, if a invoke step specifies a extra or factory property which is expecting a particular event , if there is no expected event , Canon will not throw an error or even a warning to indicate to the user that no event was found. This is a common source of errors so I think it would be good to at least default to throwing an error if a matching event is not found and also offer potentially a flag on the invoke step which allows for such errors to be suppressed if you are interacting with a contract which may not emit an event

**Comment by FuzzB0t** [comment]
@dbeal-eth I added warnings for the contract not containing any events and the cannonfile not expecting any events. Also the invoke step now throws a full on error if the cannonfile specifies an event but the invoked function does not emit that event.

The warnings can be suppressed with a new flag I added, but the error cannot be suppressed. Let me know if you have any change requests or feedback!
