### ISSUE TITLE
Eliminate explicit `depends`

### ISSUE THREAD

**Issue by dbeal-eth** [usecannon/cannon#269]
Many developers have been giving me feedback that the Canon file format is generally very easy to process. However, it is tedious to specify the depends for every single step manually, especially when it is possible to drive this information by just looking at the configuration. Implement the ability to implicitly determine dependencies for a given step. Implementation of this feature will require a combination of interpretation of configuration arguments as well as parsing of interpolated settings values. We will likely need to add a new function to the actions code which allows for the derivation of these dependencies. Note that a user can still explicitly define dependencies. If it is necessary. We should not be completely removing the depends option.

**Comment by noahlitvin** [comment]
Per discussion, suggesting this should be a warning / extra error message info rather than automatically ordering.
