### ISSUE TITLE
`cannon run` does not load package contracts in certain cases

### ISSUE THREAD

**Issue by dbeal-eth** [usecannon/cannon#278]
When running the command `cannon interact synthetix:2.90.1 --chain-id 10`, the interact tool does not recognize any contracts in the package.

However, we know this package contains a great many contracts (just look at https://usecannon.com/packages/synthetix/interact#QmWt1kz1gTRdJfRxNCcegBoSXa25UGGsmFskiR6tntZorX )

similar problems have been observed with `cannon decode synthetix:2.90.1 --chain-id 10 0x3296af230000000000000000000000000000000000000000000000000429d069189e0000` (which should be able to decode the transaction, but fails likely due to the same reason) and `cannon run synthetix:2.90.1 --chain-id 10`

**Comment by aminlatifi** [comment]
> @dbeal-eth The interact and decode commands work well for me. For instance the decode outputs
> 
> ```
> function setLiquidationBufferRatio(uint256 _ratio) 0x3296af23
>   uint256 _ratio 300000000000000000
> ```
> 
> and the interact command loads contracts well <img alt="image" width="310" src="https://user-images.githubusercontent.com/5684607/250822775-20c09c58-6f9f-4497-964f-e7d7756cf13c.png">
> 
> Are you sure the ipfs.io endpoint that you query has the object QmWt1kz1gTRdJfRxNCcegBoSXa25UGGsmFskiR6tntZorX ? maybe it needs some time to load it.
> 
> Only the run command throws `Error: anvil failed to start` error which is another error as it must try to connect to `frame`, right? do you want to make an issue for it?

The timeout issue happened for my connection issue, nothing to worry about.

**Comment by dbeal-eth** [comment]
> > @dbeal-eth The interact and decode commands work well for me. For instance the decode outputs
> > 
> > ```
> > function setLiquidationBufferRatio(uint256 _ratio) 0x3296af23
> >   uint256 _ratio 300000000000000000
> > ```
> > 
> > and the interact command loads contracts well <img alt="image" width="310" src="https://user-images.githubusercontent.com/5684607/250822775-20c09c58-6f9f-4497-964f-e7d7756cf13c.png">
> > 
> > Are you sure the ipfs.io endpoint that you query has the object QmWt1kz1gTRdJfRxNCcegBoSXa25UGGsmFskiR6tntZorX ? maybe it needs some time to load it.
> > 
> > Only the run command throws `Error: anvil failed to start` error which is another error as it must try to connect to `frame`, right? do you want to make an issue for it?
> 
> The timeout issue happened for my connection issue, nothing to worry about.

Oh yes, thank you for your reply. It appears to be an issue with my system having a different IPFS hash. I'm going to figure out what happened and maybe this is in fact a different issue. Thank you
