### ISSUE TITLE
Unable to find out/Contract.sol/Contract.json 

### ISSUE THREAD

**Issue by avniculae** [usecannon/cannon#281]
Cannon versions > 2.4.14 are unable to find artifact files when running `cannon build cannonfiles/file.toml`. The command is run in the same folder where `out/` and `src/` are; however, note that the cannon file is not in the same directory, but rather in the `cannonfiles` folder.

**Comment by dbeal-eth** [comment]
@avniculae hello! thanks for this report! could you please output the result of `forge config --json` from your project? in particular we are interested in the `out` config option

**Comment by dbeal-eth** [comment]
also you mentioned that your cannonfile was in a sub-directory? does that mean the command you are executing to build your project is in the form `cannon build cannon/package.toml`?
