### ISSUE TITLE
Infinite loop and deps tree resolution

### ISSUE THREAD

**Issue by noahlitvin** [usecannon/cannon#292]
via @noisekit

Ok this might be a bit trickier to explain but I'll try (there are two issues related to deps resolution and I believe one is a result of another)

I can send cannon's dependency resolver into an infinite loop.

I have noticed there was a check for "unnecessary" dependency - when 
Y depends on X
Z depends on Y
but also Z depends on X (adding X to Z would invoke error)

First problem - dependency management should account for this and actuctually require X for Z because Z uses smth from X directly and thus must declare it. Dev must not think that "oh, X is already deployd by Y so I should not declare it in Z because Z already depend on Y". It breaks isolation/independence and makes developer keep all context (deps tree) in the head all the time instead of a machine sorting this out. Plus that is exactly how any other deps management systems work (look at NPM as a good example)

Second problem is that because deps resolution is written in a way that any dep must be declared once (basing this on the error from above), as soon as there is a legit dependency on deeper levels - it cannot track that and goes into an infinite loop.

Example would be a bit more involved:
contract.P
contract.R depends on contract.P
contract.A
contract.B
invoke A.do-smth depends on A and R
invoke P.do-smth-else, depends on A, B and P ---- This leads to a cycle where A depends on R, P depends on A, R depends on P.

So there is no longer a nice tree. This has to be solved automatically but it is not and as a dev I need to solve the tree myself and make sure everything is in order without "branches" repeating anywhere 
Image
in an idealistic scenario that looks like a loop yes but because we are dealing with deployed contracts and inherently imperative code here (step by step deployments) - it is really not, as P is supposed to be deployed already before R and others and simply needs to be re-used in step 6 without issues, but it is not. 
Dependency resolver needs to understand when smth is already dependency of smth else and reuse the reference to it. Or maybe do something else.

this is the forever loop with debug
<img width="290" alt="image-1" src="https://github.com/usecannon/cannon/assets/335975/5fe25216-43ee-40a6-9f94-fd23775345b7">

The issue is that without declaring dependency in depends (because it was implicitly deployed already) it does not come up in a context so there is no way around it (as I hoped there would be).

**Comment by FuzzB0t** [comment]
Closed with #325
