### ISSUE TITLE
`npx cannon`: prints out upgrade warning when not needed

### ISSUE THREAD

**Issue by dbeal-eth** [usecannon/cannon#30]
![image](https://user-images.githubusercontent.com/2107457/186048881-c048c235-d24f-4122-8bd8-6047bde0e18c.png)

this warning should not appear for development builds

**Comment by mjlescano** [comment]
Dist tags already fixed :)

<img width="273" alt="Screenshot 2022-08-24 at 17 24 09" src="https://user-images.githubusercontent.com/558901/186458270-ba2fc8d1-76dd-4ad7-9dc0-542581e7f26e.png">
