### ISSUE TITLE
Require chain id for publish command 

### ISSUE THREAD

**Issue by noahlitvin** [usecannon/cannon#337]
Publish command should error unless chain id is provided. Currently it'll just run and not publish anything (display an empty receipts array)

**Comment by mohammadranjbarz** [comment]
@noahlitvin 
Now if user doesnt provide `chaindId` we set a default value (`13370`) for that
https://github.com/usecannon/cannon/blob/bf3a799eebe9af0424aa8b644bdd60356019f698/packages/cli/src/index.ts#L340
So it can't be empty, even if we don't set default value for that, the publish command has  a default value for chainId as well, so it's not possible to call publish function without `chainId`
https://github.com/usecannon/cannon/blob/main/packages/cli/src/commands/publish.ts#L19-L29

What should I do now?

**Comment by mohammadranjbarz** [comment]
After talking with @noahlitvin  in the call, we decided to remove default value for `chainId` and force user to provide it
