### ISSUE TITLE
Unexpected provider usage when publishing

### ISSUE THREAD

**Issue by noahlitvin** [usecannon/cannon#338]
If a user has `registryProviderUrl` set in their settings.json and does not provide a private-key param to publish, I would expect it to attempt to open Frame. I think it should error that the private key settings is required in this case, if not open Frame instead. cc @dbeal-eth

**Comment by mohammadranjbarz** [comment]
@noahlitvin  Added this explanation in Discord:
* If private key provided
  *  Try RPC in settings if available
  * Otherwise try eth-provider
* else
  * Use eth-provider
  * Put a warning in the console that it's skipping the RPC in settings (if it's there) because --private-key was not supplied
