### ISSUE TITLE
Clarify subpackage publishing errors

### ISSUE THREAD

**Issue by noahlitvin** [usecannon/cannon#339]
Publishing packages automatically attempts to publish provisioned subpackages. The owner of the top-level package may not own the subpackage namespaces. Either this error should be clearer, or the user should be warned prior to publish, but either way, it should be possible to publish.

Also, we should probably make it more clear in the CLI output that the subpackages are being published when they are.

cc @dbeal-eth - preferences on the behavior here?

**Comment by aminlatifi** [comment]
> 

@noahlitvin I suppose the subpackage must be defined like this

<img width="613" alt="image" src="https://github.com/usecannon/cannon/assets/5684607/16cacad0-e183-43a5-98c6-0f603c4aba78">


https://github.com/Synthetixio/synthetix-deployments/blob/main/tomls/core.toml


Am I right?
