### ISSUE TITLE
error is not clear on chart not found

### ISSUE THREAD

**Issue by noahlitvin** [usecannon/cannon#4]
if you attempt to download a chart that doesnt exist, you get an error says "Unexpected token Q in JSON at position 0"

the error should be "Chart not found on registry" or something like that

(originally https://github.com/usecannon/cannon-legacy/issues/52)

**Comment by dbeal-eth** [comment]
when I run the following command with latest cannon

```
➜  cannon git:(main) npx cannon hello-world
```

I get:

```
Error: package not found: hello-world:latest. please check that the requested package exists and try again.
```

seems to be resolved
