### ISSUE TITLE
bug(cli): freeze on `forge build` failure

### ISSUE THREAD

**Issue by dbeal-eth** [usecannon/cannon#408]
if `forge build` fails due to a compiler error or something, cannon will hang indefinitely without printing anything.

This is testable on the sample foundry project by causing a compilation error in a file, and then running `$CANNON build`.

**Comment by FuzzB0t** [comment]
Can you provide a screenshot of this happening? I tested with a compilation error in the sample foundry project and got a valid error:

![image](https://github.com/usecannon/cannon/assets/30664234/12cec5e1-2b6c-416a-b546-fdad41c22ace)
