### ISSUE TITLE
Network list is weird/too long

### ISSUE THREAD

**Issue by noahlitvin** [usecannon/cannon#426]
There are too many options in the network selection ui from rainbowkit. Can we adjust the UI, at least make it easy to find more common networks?

**Comment by 0xDmitry** [comment]
@noahlitvin just to be sure, you mean these options? 
<img width="1792" alt="Screenshot 2023-09-11 at 19 43 57" src="https://github.com/usecannon/cannon/assets/61683409/93056bfd-2b27-45a4-ba3c-f548cfcdbb86">

**Comment by noahlitvin** [comment]
@0xDmitry yep
