### ISSUE TITLE
Show more data on queued tx component

### ISSUE THREAD

**Issue by noahlitvin** [usecannon/cannon#432]
Number of signatures, time staged, whatever other info we have available:
<img width="780" alt="s" src="https://github.com/usecannon/cannon/assets/335975/7759de19-ec52-44b7-bbe4-4cd488616d04">

**Comment by 0xDmitry** [comment]
@noahlitvin Only for queued or executed also?

<img width="1792" alt="Screenshot 2023-09-14 at 12 28 27" src="https://github.com/usecannon/cannon/assets/61683409/b0c9153e-dbab-425d-9393-2695a7dba550">
