### ISSUE TITLE
Improve CLI output for publish command

### ISSUE THREAD

**Issue by noahlitvin** [usecannon/cannon#435]
We're consistently seeing an error on publish, but then it works?
![image](https://github.com/usecannon/cannon/assets/335975/597f4066-f945-41b4-a0d4-180c32b525ec)

Let's also improve the CLI output to be:
`Pinned qM..... to the remote ipfs url (Run cannon setup to reconfigure)`
`Published qM... to the registry as synthetix:latest@main with 0x.... (Transaction hash: 0x....)`
`Published qM... to the registry as synthetix:3.2.1@main with 0x....`

related to #353 and #421

**Comment by FuzzB0t** [comment]
Found this discussion which is related to the error message on estimating gas:

https://github.com/ethers-io/ethers.js/discussions/1944

The solution seems to be to set a default on MaxGasPerFee and MaxPriorityGasFee

https://github.com/ethers-io/ethers.js/discussions/1944#discussioncomment-3743181
