### ISSUE TITLE
`publish` could pull deployment file from IPFS or fail

### ISSUE THREAD

**Issue by noisekit** [usecannon/cannon#440]
Running cannon publish to update `latest` tag does not do anything, just exists without any error

Command would be smth like this:
```sh
cannon publish synthetix:3.3.4 --tags latest
```

The debug output:
```sh
 2023-09-12T02:28:36.295Z cannon:cli:registry scanning deploys in: .local/share/cannon/tags [
   'synthetix-local_0.0.1_13370-main.txt.meta',
   'synthetix-local_latest_13370-main.txt.meta'
 ]
 2023-09-12T02:28:36.295Z cannon:cli:registry looking for /^synthetix:3.3.4$/, /^13370-main$/
 {
   "packageRef": "synthetix:3.3.4",
   "tags": [
     "latest"
   ],
   "registrationReceipts": []
 }
 Process exited (exit code 0), completed in 1s 20ms
```

Expected behaviour:
1. Pull package from IPFS
2. Publish with updated tag

Alternatively:
1. Fail with error that package does not exist locally
2. Provide and suggest a way to pull package to local

NOTE: I reckon cannon should not publish (tag!) from local at all. Package can only be deployed to the registry with specific version. Then we tag already published version.

**Comment by FuzzB0t** [comment]
Closed in favor of #280
