### ISSUE TITLE
Automatically load Safes associated with a connected wallet

### ISSUE THREAD

**Issue by noahlitvin** [usecannon/cannon#451]
<img width="769" alt="Screenshot 2023-09-13 at 11 01 48 PM" src="https://github.com/usecannon/cannon/assets/335975/443d6904-ade7-478c-9a98-5365bf2f6a18">
Ideally this could pull from across all chains.

**Comment by 0xDmitry** [comment]
@noahlitvin it works actually, we just need to configure Infura project that was used on https://deploy.usecannon.com/ for the new host
<img width="1792" alt="Screenshot 2023-09-14 at 12 28 27" src="https://github.com/usecannon/cannon/assets/61683409/e8159ca3-5e01-4815-8e28-8e357f989405">
