### ISSUE TITLE
allow debug logging of only `console.log` solidity output

### ISSUE THREAD

**Issue by dbeal-eth** [usecannon/cannon#83]
Right now if a user wants to get `console.log` debug output, they have to run `DEBUG=cannon:rpc:cli ` to the beginning of their testing command. However, there are a couple of problems with this:
1) the knowledge of this is very limited and hard to know about 
2) the output includes a lot of extra anvil output which is not important/useful for the user

instead, we should provide either a parameter or an easy environment variable which toggles on tracing of transactions using the cannon provider wrapper. If it sees a successful transaction and the flag is enabled, the wrapper will:
1. perform `trace_transaction` call to get the trace
2. output something both human friendly and informative. for example: `console.log: AccountModule.delegateCollateral(): I am a test console log!`

**Comment by noahlitvin** [comment]
Implement with env var please.
